version: '3.4'

services:

  mysql_server:
    build: ./dockerfile-mysql/
    image: wjma90/mysql_dummy:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=geoserviciosbd
      - MYSQL_USER=app
      - MYSQL_PASSWORD=toor
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password

  monolito:
    build: ./monolito/
    image: wjma90/monolito:latest
    container_name: monolito
    environment: 
      - host=mysql_server
      - username=root
      - password=toor
      - clientId=46n55acsbp53cm3hf9bsjc9h00
      - userPoolId=us-east-1_qqm7RWPtD
      - aws_Region=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY:-AKIA4SMRFI24HAJM5CG5}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-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}
    depends_on: 
      - mysql_server
    ports:
      - "80:8090"
    restart: on-failure
    entrypoint: dockerize -wait tcp://mysql_server:3306 -timeout 10m java -jar /app.jar

  frontend:
    build: ./angular/
    image: wjma90/frontend-curso:latest
    container_name: frontend
    depends_on: 
      - monolito
    ports:
      - "8100:80"
    restart: on-failure
    entrypoint: dockerize -wait http://monolito:8090/v2/api-docs -timeout 10m nginx -g 'daemon off;'

  sauceconnect:
      image: wjma90/sauceconnect:latest
      container_name: sauceconnect
      command:
        - -u
        - ${SAUCELABS_ACCESS_USR:-javadevops}
        - -k
        - ${SAUCELABS_ACCESS_PSW:-eeca871b-437c-4299-b02e-61a5b9d21633}
        - -i
        - ${TUNNEL_SAUCECONNECT:-javadevops}
      ports:
      - "4445:4445"
      - "8032:8032"
      #network_mode: "host"